15 make icons + text on contact page hyperlinked
ReStore-TRD/ReStore_Website pull request #18
Opened 2022-10-06 12:43 UTC by NeerajMehta04

Contacts_icon+text link

2022-10-06 13:09 UTC, quarc0o commented on contact.html
> +                        <a href="https://www.instagram.com/restore.trdxals/?hl=en" >
add: target=”_blank” to the anchor tags so that the link opens in a new window

2022-10-06 13:10 UTC, quarc0o requested changes
I made some comments 😁

2022-10-07 07:30 UTC, quarc0o commented
Wrong branch 😅

2022-10-07 07:32 UTC, quarc0o commented
Wrong branch 😅

2022-10-07 07:33 UTC, quarc0o submitted a review, later dismissed
Wrong branch 😅

2022-10-11 18:11 UTC, ReStore-TRD approved these changes

2022-10-11 18:13 UTC, merged