39 navbar
ReStore-TRD/restore_website pull request #46
Opened 2023-12-19 09:54 UTC by Dorsa74

2023-12-21 06:51 UTC, quarc0o requested changes
Very nice! Let me know if iyou have any questions! 😁

2023-12-21 06:51 UTC, quarc0o commented on app/components/navigation/navbar/Logo.tsx
Good, but instead of checking the width with the useState hook, we should instead do it through tailwind responsive design: https://tailwindcss.com/docs/responsive-design

This will give less code which is good, but the most important is that we can get rid of the "use client" and render the navbar on the server instead of the client, which means better performance.

2023-12-21 06:51 UTC, quarc0o commented on app/components/navigation/navbar/index.tsx
> +                </li>
remove the outer <li> and the inner <p> tag - we onlu need the next Link, which can be styled directly

2023-12-25 18:24 UTC, Dorsa74 commented on app/components/navigation/navbar/index.tsx
> +                </li>
Thanks Emmanuel! I removed the list elements and it is less code now :)

2023-12-25 18:26 UTC, Dorsa74 commented on app/components/navigation/navbar/Logo.tsx
Oh, ok! 

Now I have removed "use client". not sure if it is responsive though, can you please check that?

2024-02-16 16:49 UTC, merged